"""Add is_cancel Cash Deposit Model

Revision ID: 730700bea9bf
Revises: 898865c741ae
Create Date: 2021-07-02 08:08:38.383627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730700bea9bf'
down_revision = '898865c741ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_deposit', sa.Column('is_cancel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_deposit', 'is_cancel')
    # ### end Alembic commands ###
