"""Cash Model Fix

Revision ID: 7baa5eaa088a
Revises: cd60d12163c7
Create Date: 2021-06-30 05:03:36.512900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baa5eaa088a'
down_revision = 'cd60d12163c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
