"""Cash Model Fix

Revision ID: 898865c741ae
Revises: 7baa5eaa088a
Create Date: 2021-06-30 05:17:50.111403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898865c741ae'
down_revision = '7baa5eaa088a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
