"""Cash Model Fix

Revision ID: 9835cb1b0be6
Revises: e00327fff4a5
Create Date: 2021-06-30 01:55:19.238550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9835cb1b0be6'
down_revision = 'e00327fff4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
