"""Cash Model Fix

Revision ID: a4e29ad0f3aa
Revises: 9835cb1b0be6
Create Date: 2021-06-30 01:57:13.744091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e29ad0f3aa'
down_revision = '9835cb1b0be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
