"""Cash Model Fix

Revision ID: cd60d12163c7
Revises: a4e29ad0f3aa
Create Date: 2021-06-30 05:01:24.318889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd60d12163c7'
down_revision = 'a4e29ad0f3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
