"""add is_complete

Revision ID: 498df036be30
Revises: 1a289e675bbc
Create Date: 2021-04-01 02:20:17.414072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498df036be30'
down_revision = '1a289e675bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'is_complete')
    # ### end Alembic commands ###
