"""fix type int to GUID at id for Cash Deposit Model

Revision ID: 62c63483ce05
Revises: 730700bea9bf
Create Date: 2021-07-07 05:43:58.590106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c63483ce05'
down_revision = '730700bea9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_deposit', 'id',
               existing_type=sa.INTEGER(),
               type_=app.models._guid.GUID(),
               existing_nullable=False)
    op.drop_index('ix_cash_deposit_id', table_name='cash_deposit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cash_deposit_id', 'cash_deposit', ['id'], unique=False)
    op.alter_column('cash_deposit', 'id',
               existing_type=app.models._guid.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
