"""empty message

Revision ID: 98650d55548c
Revises: a0c7dace750e
Create Date: 2021-08-18 10:16:28.646860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98650d55548c'
down_revision = 'a0c7dace750e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
