"""Update cash_deposit(due_date)

Revision ID: a0c7dace750e
Revises: 0c47e9ff5e84
Create Date: 2021-07-09 07:00:53.700380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c7dace750e'
down_revision = '0c47e9ff5e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_deposit', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_deposit', 'due_date')
    # ### end Alembic commands ###
