"""back_populates

Revision ID: cce4596651f2
Revises: 498df036be30
Create Date: 2021-04-01 03:09:57.259106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce4596651f2'
down_revision = '498df036be30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
