"""empty message

Revision ID: f45bbfddfabe
Revises: cce4596651f2
Create Date: 2021-04-22 00:29:46.977662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45bbfddfabe'
down_revision = 'cce4596651f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('view_count', sa.Integer(),
                                       server_default="0", default=0, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'view_count')
    # ### end Alembic commands ###
